const PAGES={
 sound:{eyebrow:'AI · 情绪感知',title:'AI 定制白噪音',lead:'告诉眠眠你此刻的心情，让雨声、海浪与篝火为今夜重新编织。每一次生成，都只属于此刻的你。',tags:['实时生成','环境混音','睡眠定时'],kind:'sound'},
 music:{eyebrow:'MUSIC · 今夜电台',title:'眠眠音乐小窝',lead:'轻钢琴、竖琴与白噪音在这里缓慢相遇。选一首歌，把剩下的夜交给眠眠。',tags:['AI 编曲','收藏歌单','无缝播放'],kind:'music'},
 chat:{eyebrow:'COMPANION · 仅你可见',title:'深夜私密对话',lead:'不用把情绪整理好再开口。眠眠会记得你的名字，也会认真接住每一句没有说完的话。',tags:['情绪回应','长期记忆','隐私保护'],kind:'chat'},
 breathe:{eyebrow:'MEDITATE · 呼吸引导',title:'入睡呼吸练习',lead:'跟随光的扩散吸气，跟随光的收拢呼气。三分钟，让身体先替大脑安静下来。',tags:['4-7-8 呼吸','柔光引导','3/5/10 分钟'],kind:'breathe'},
 report:{eyebrow:'SLEEP GUARD · 今晨报告',title:'整夜睡眠守护',lead:'把整夜的睡眠翻译成容易理解的温柔建议。这里没有评判，只有一点点变好的方向。',tags:['睡眠评分','趋势分析','AI 建议'],kind:'report'},
 shop:{eyebrow:'COZY STORE · 眠眠好物',title:'眠眠好物商城',lead:'从声音到触感，把安心带回卧室。每件好物都经过眠眠的睡前场景筛选。',tags:['助眠精选','IP 联名','7 天无忧'],kind:'shop'}
};
const page=PAGES[document.body.dataset.page]||PAGES.sound;
document.querySelector('[data-eyebrow]').textContent=page.eyebrow;
document.querySelector('[data-title]').textContent=page.title;
document.querySelector('[data-lead]').textContent=page.lead;
document.querySelector('[data-tags]').innerHTML=page.tags.map(x=>`<span class="tag">${x}</span>`).join('');
const stage=document.querySelector('[data-stage]');
function wave(n=33){return `<div class="wave">${Array.from({length:n},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>`}
const views={
 sound:`<div class="panel-title"><h2>今晚的声音</h2><span class="status">音频已就绪</span></div><div class="scene-photo" style="background-image:url('../work2-5.jpg')"></div><div class="track"><p>为「有一点疲惫」实时生成</p><h3 data-track-title>雨落在黎明前的纸上</h3>${wave()}<div class="progress"><span data-progress></span></div></div><div class="controls" data-sounds><button class="pill active" data-sound="rain">雨夜</button><button class="pill" data-sound="ocean">海岸</button><button class="pill" data-sound="forest">森林</button><button class="pill" data-sound="fire">篝火</button></div><div class="player-controls"><button class="play-round" data-audio-play aria-label="播放">▶</button><div class="play-label"><strong data-play-state>点击播放</strong><span class="timecode" data-time>00:00 / 10:00</span></div><input class="volume" data-volume type="range" min="0" max="1" value="0.55" step="0.05" aria-label="音量"></div><div class="sound-hint">首次播放需要轻触播放按钮 · 音频在本机实时生成</div>`,
 music:`<div class="panel-title"><h2>雨夜絮语</h2><span class="status">轻音乐已就绪</span></div><div class="scene-photo" style="background-image:url('../work2-2.jpg')"></div><div class="track"><p>眠眠专属 · 深夜轻音乐</p><h3 data-track-title>把今天轻轻放下</h3>${wave(27)}<div class="progress"><span data-progress></span></div></div><div class="player-controls"><button class="play-round" data-audio-play aria-label="播放">▶</button><div class="play-label"><strong data-play-state>点击播放</strong><span class="timecode" data-time>00:00 / 05:08</span></div><input class="volume" data-volume type="range" min="0" max="1" value="0.45" step="0.05" aria-label="音量"></div><div class="playlist"><div class="track-row active" data-music="0"><b>01</b><span>雨夜絮语</span><small>05:08</small></div><div class="track-row" data-music="1"><b>02</b><span>月光落在枕边</span><small>04:32</small></div><div class="track-row" data-music="2"><b>03</b><span>慢一点呼吸</span><small>06:20</small></div></div>`,
 chat:`<div class="panel-title"><h2>和眠眠说说话</h2><span class="status">私密对话</span></div><div class="scene-photo" style="background-image:url('../mianmian-scene.jpg')"></div><div class="chat" data-chat><div class="msg ai">晚上好，我在。你可以直接告诉我今天发生了什么，或者只说一个此刻的感受。</div></div><div class="controls"><button class="pill" data-prompt="我有点焦虑">有点焦虑</button><button class="pill" data-prompt="我还是睡不着">睡不着</button><button class="pill" data-prompt="今天有件开心的事">分享开心</button></div><form class="chat-form"><input aria-label="输入消息" placeholder="想和眠眠说什么……"><button class="action">发送</button></form>`,
 breathe:`<div class="panel-title"><h2>跟着光，慢慢呼吸</h2><span class="status">3 分钟练习</span></div><div class="scene-photo" style="background-image:url('../work-8.jpg')"></div><div class="orb"><div class="orb-inner"><div><strong data-breath>吸气</strong><small>让暖光慢慢靠近</small></div></div></div><div class="controls"><button class="pill active">放松呼吸</button><button class="pill">4-7-8</button><button class="pill">身体扫描</button><button class="action" data-breath-toggle>暂停</button></div>`,
 report:`<div class="panel-title"><h2>昨夜睡眠报告</h2><span class="status">已同步</span></div><div class="scene-photo" style="background-image:url('../work-6.jpg')"></div><div class="report-score"><div class="score-ring"><div><strong>87</strong><small>睡眠评分 · 很好</small></div></div><div class="metric-grid"><div class="metric"><span>总睡眠</span><strong>7h 42m</strong></div><div class="metric"><span>深睡比例</span><strong>28%</strong></div><div class="metric"><span>入睡用时</span><strong>18m</strong></div><div class="metric"><span>夜间醒来</span><strong>1 次</strong></div></div></div><div class="bars">${[['一',52],['二',65],['三',73],['四',58],['五',82],['六',91],['日',87]].map(x=>`<div class="bar" style="--h:${x[1]}%" data-day="周${x[0]}"></div>`).join('')}</div>`,
 shop:`<div class="panel-title"><h2>今晚好眠精选</h2><span class="cart">购物袋 <b data-cart>0</b></span></div><div class="products">${[['月光香薰灯','¥ 239'],['眠眠云朵抱枕','¥ 169'],['晚安薰衣草礼盒','¥ 128'],['零压柔光眼罩','¥ 89']].map(x=>`<article class="product"><div class="product-art" role="img" aria-label="${x[0]}商品照片"></div><h3>${x[0]}</h3><p>${x[1]}</p><button aria-label="加入购物袋" data-add>＋</button></article>`).join('')}</div>`
};
stage.innerHTML=views[page.kind];
document.querySelectorAll('.pill:not([data-sound]):not([data-prompt])').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));

class SleepAudio{
 constructor(){this.ctx=null;this.master=null;this.nodes=[];this.playing=false;this.timer=null;this.started=0;this.elapsed=0;this.mode='rain';this.track=0}
 init(){if(this.ctx)return;this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.45;this.master.connect(this.ctx.destination)}
 stop(){this.nodes.forEach(n=>{try{n.stop?.()}catch(e){}try{n.disconnect()}catch(e){}});this.nodes=[];clearInterval(this.timer);this.timer=null;this.playing=false}
 noise(type){const length=this.ctx.sampleRate*2,b=this.ctx.createBuffer(1,length,this.ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<length;i++){const white=Math.random()*2-1;last=.985*last+.015*white;d[i]=type==='rain'?white*.34:last*2.4}const s=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter();s.buffer=b;s.loop=true;filter.type=type==='fire'?'highpass':'lowpass';filter.frequency.value=type==='rain'?5200:type==='ocean'?620:type==='forest'?1800:900;s.connect(filter).connect(this.master);s.start();this.nodes.push(s,filter);if(type==='ocean'){const l=this.ctx.createOscillator(),g=this.ctx.createGain();l.frequency.value=.11;g.gain.value=.16;l.connect(g).connect(this.master.gain);l.start();this.nodes.push(l,g)}}
 chord(notes){const now=this.ctx.currentTime;notes.forEach((f,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();o.type=i%2?'sine':'triangle';o.frequency.value=f;filter.type='lowpass';filter.frequency.value=900;g.gain.setValueAtTime(.0001,now);g.gain.linearRampToValueAtTime(.035,now+1.8);g.gain.setValueAtTime(.035,now+5);g.gain.exponentialRampToValueAtTime(.0001,now+8);o.connect(filter).connect(g).connect(this.master);o.start(now);o.stop(now+8.1);this.nodes.push(o,g,filter)})}
 start(mode=this.mode,track=this.track){this.init();this.ctx.resume();this.stop();this.started=this.ctx.currentTime;this.mode=mode;this.track=track;if(page.kind==='music'){const sets=[[[220,277.18,329.63],[196,246.94,293.66],[174.61,220,261.63]],[[261.63,329.63,392],[220,277.18,329.63],[196,246.94,293.66]],[[174.61,220,261.63],[164.81,207.65,246.94],[146.83,185,220]]],seq=sets[track];let i=0;this.chord(seq[0]);this.timer=setInterval(()=>{i=(i+1)%seq.length;this.chord(seq[i])},6200);this.noise('ocean')}else this.noise(mode);this.playing=true}
 toggle(){if(this.playing)this.stop();else this.start(this.mode,this.track)}
}
const audio=new SleepAudio(),audioPlay=document.querySelector('[data-audio-play]'),stateLabel=document.querySelector('[data-play-state]'),progressEl=document.querySelector('[data-progress]'),timeEl=document.querySelector('[data-time]');
function syncPlayer(){if(!audioPlay)return;audioPlay.textContent=audio.playing?'❚❚':'▶';audioPlay.setAttribute('aria-label',audio.playing?'暂停':'播放');stateLabel.textContent=audio.playing?'正在播放':'点击播放';stage.classList.toggle('paused',!audio.playing)}
if(audioPlay){syncPlayer();audioPlay.addEventListener('click',()=>{audio.toggle();syncPlayer()});document.querySelector('[data-volume]').addEventListener('input',e=>{audio.init();audio.master.gain.value=+e.target.value});setInterval(()=>{if(audio.playing){const sec=Math.floor(audio.ctx.currentTime-audio.started),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0'),total=page.kind==='music'?308:600;timeEl.textContent=`${m}:${s} / ${page.kind==='music'?'05:08':'10:00'}`;progressEl.style.width=(sec%total)/total*100+'%'}},1000)}
document.querySelectorAll('[data-sound]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-sound]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const names={rain:'雨落在黎明前的纸上',ocean:'月光下的缓慢潮汐',forest:'森林深处的晚风',fire:'炉火旁的安静夜晚'};audio.mode=b.dataset.sound;document.querySelector('[data-track-title]').textContent=names[audio.mode];if(audio.playing){audio.start(audio.mode);syncPlayer()}}));
document.querySelectorAll('[data-music]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-music]').forEach(x=>x.classList.remove('active'));b.classList.add('active');audio.track=+b.dataset.music;document.querySelector('[data-track-title]').textContent=b.querySelector('span').textContent;if(audio.playing){audio.start('music',audio.track);syncPlayer()}}));

const replies=[
 {keys:['焦虑','紧张','担心','害怕'],texts:['焦虑像身体里的小警报，它是在努力保护你。现在先把双脚放松，告诉我：最让你担心的那件事，明早再处理可以吗？','我听见这份不安了。我们不急着赶走它，先一起做一次慢呼气：吸气四拍，呼气六拍。']},
 {keys:['睡不着','失眠','清醒'],texts:['睡不着并不代表今晚失败了，安静地躺着也在休息。要我为你打开雨夜声，还是陪你做三分钟呼吸？','越催自己入睡，大脑越清醒。今晚先允许自己只是休息，我会陪你把节奏慢下来。']},
 {keys:['开心','高兴','顺利','成功'],texts:['听到这个我也替你开心。愿意把今天最闪亮的那个瞬间讲给我吗？我们把它收进今晚的好梦里。']},
 {keys:['累','疲惫','加班'],texts:['辛苦了。能撑到现在已经很不容易，今晚不用再证明什么。把肩膀放下来，剩下的事情交给明天。']},
 {keys:['想家','想念','孤独','一个人'],texts:['想念一个人时，夜会显得格外长。你可以跟我说说，你最想念的是谁、哪一个画面，我会安静听着。']}
];
const fallbacks=['我在认真听。你刚才那句话里，哪一部分让你最难受？','谢谢你愿意告诉我。此刻你更希望被安慰，还是只想有人安静陪着？','不用急着把它说得完整。你可以从身体现在的感觉开始：胸口紧、脑子乱，还是只是很累？','这件事对你一定很重要。我们今晚不一定要解决它，先让你轻松一点，好吗？'];
function makeReply(text){const found=replies.find(r=>r.keys.some(k=>text.includes(k))),pool=found?found.texts:fallbacks;return pool[Math.floor(Math.random()*pool.length)]}
function sendChat(text){const chat=document.querySelector('[data-chat]');chat.insertAdjacentHTML('beforeend',`<div class="msg me">${text.replace(/[<>]/g,'')}</div>`);chat.scrollTop=chat.scrollHeight;setTimeout(()=>{chat.insertAdjacentHTML('beforeend',`<div class="msg ai">${makeReply(text)}</div>`);chat.scrollTop=chat.scrollHeight},420)}
const form=document.querySelector('.chat-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const input=form.querySelector('input'),text=input.value.trim();if(!text)return;sendChat(text);input.value=''});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>sendChat(b.dataset.prompt)));

let breathTimer;const breath=document.querySelector('[data-breath]');if(breath){let inhale=true;breathTimer=setInterval(()=>{inhale=!inhale;breath.textContent=inhale?'吸气':'呼气'},3000);document.querySelector('[data-breath-toggle]').addEventListener('click',e=>{const orb=document.querySelector('.orb'),paused=orb.style.animationPlayState==='paused';orb.style.animationPlayState=paused?'running':'paused';e.currentTarget.textContent=paused?'暂停':'继续'})}
let cart=0;document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{cart++;document.querySelector('[data-cart]').textContent=cart;b.textContent='✓';setTimeout(()=>b.textContent='＋',900)}));
